### ISSUE TITLE
How to download files from github to install on onyx.

### ISSUE THREAD

**Issue by vicgh1** [ubports-onyx/ubports-ci#2]
I have joined github to learn what to do and still not sure how I can learn and contribute to this project. I am using Ubuntu 20.04.
Please advise what I need to do to install ubports 7.1 on my device.

Thanks

**Comment by ittat** [comment]
Hi @vicgh1. Can you tell me your device model? Onyx？

**Comment by vicgh1** [comment]
Hi @ittat .
I have the OnePlus X.

Thanks

**Comment by vicgh1** [comment]
I could not follow through on the install guide on XDA developers and github.
   3. You need system.img , halium-boot and latest ubports-touch rootfs
   * Download system & halium-boot from {Mod edit}

**Comment by ittat** [comment]
1. you need to update your onyx to "OXYGENOS 3.1.3/3.1.4 FIRMWARE" or Android 6.0 +
2. Download the newly built image (the system & halium-boot) to your computer : https://github.com/ubports-onyx/ubports-ci/actions/runs/191014344
3. Download ubports-touch.rootfs-xenial-armhf.tar.gz to your computer: https://github.com/ubports-onyx/ubports-ci/releases/tag/ubports-touch.rootfs-xenial

**Comment by ittat** [comment]
And the guide about how to install ubports in here: http://docs.ubports.com/en/latest/porting/installing-16-04.html

**Comment by ittat** [comment]
Step 1 - Install halium-boot : http://docs.ubports.com/en/latest/porting/installing-16-04.html#install-halium-boot

Step 2 - Install system.img and rootfs : http://docs.ubports.com/en/latest/porting/installing-16-04.html#install-system-img-and-rootfs

**Comment by vicgh1** [comment]
Thanks so much.
I struggled to locate the the system and halium-boot from within github. I have been scratching my head as to where to find them. I see 'actions' and then 'runs'
Really helpful.

**Comment by ittat** [comment]
In addition, some time ago I tried to porting ubports-9.0, but without success :( 
I get some kernel crashes when booting it. Because of time, I haven't fixed it yet. 
And I put the experimental manifest for ubports-9.0 here：https://github.com/OnePlus-onyx/build-CI/blob/1603875e178cd29ca65cf506ab564a703ee93463/.github/workflows/ut-9.0.yml#L59-L64
